(keymap-global-set "C-z" 'undo)
(keymap-global-set "C-x C-z" 'nil)
(keymap-global-set "<insert>" 'nil)
(keymap-global-set "C-b" nil)
(keymap-global-set "C-x C-b" nil)
(keymap-global-set "C-x b" nil)
(keymap-global-set "C-b C-p" 'switch-to-prev-buffer)
(keymap-global-set "C-b b" 'switch-to-buffer)
(keymap-global-set "C-b C-b" 'ibuffer)
(keymap-global-set "C-b C-k" 'kill-buffer)
(keymap-global-set "C-b C-s" (lambda() (interactive) (switch-to-buffer "*scratch*")))
(keymap-global-set "C-s" 'isearch-forward)
(keymap-global-set "C-M-s" 'isearch-backward)
(keymap-global-set "C-S-s" 'isearch-backward)
(keymap-global-set "C-r" 'query-replace)
(keymap-global-set "C-o" 'other-window)
(keymap-global-set "C-x o" 'nil)
(keymap-global-set "S-DEL" 'kill-whole-line)
(keymap-global-set "M-1" 'delete-other-windows)
(keymap-global-set "M-2" 'split-window-below)
(keymap-global-set "M-3" 'split-window-right)
(keymap-global-set "M-0" 'delete-window)
(keymap-set ctl-x-map "v" 'nil)

(provide 'init-global-keybindings)
