(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(load-theme 'darktooth t)
(setq solarized-high-contrast-mode-line t)
(setq solarized-distinct-fringe-background t)
(add-to-list 'default-frame-alist '(font . "PragmataPro-10"))
